package com.tianniu.pojo;

import java.util.ArrayList;
import java.util.List;

public class MemberConsumerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public MemberConsumerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMemberconsumeridIsNull() {
            addCriterion("MEMBERCONSUMERID is null");
            return (Criteria) this;
        }

        public Criteria andMemberconsumeridIsNotNull() {
            addCriterion("MEMBERCONSUMERID is not null");
            return (Criteria) this;
        }

        public Criteria andMemberconsumeridEqualTo(Short value) {
            addCriterion("MEMBERCONSUMERID =", value, "memberconsumerid");
            return (Criteria) this;
        }

        public Criteria andMemberconsumeridNotEqualTo(Short value) {
            addCriterion("MEMBERCONSUMERID <>", value, "memberconsumerid");
            return (Criteria) this;
        }

        public Criteria andMemberconsumeridGreaterThan(Short value) {
            addCriterion("MEMBERCONSUMERID >", value, "memberconsumerid");
            return (Criteria) this;
        }

        public Criteria andMemberconsumeridGreaterThanOrEqualTo(Short value) {
            addCriterion("MEMBERCONSUMERID >=", value, "memberconsumerid");
            return (Criteria) this;
        }

        public Criteria andMemberconsumeridLessThan(Short value) {
            addCriterion("MEMBERCONSUMERID <", value, "memberconsumerid");
            return (Criteria) this;
        }

        public Criteria andMemberconsumeridLessThanOrEqualTo(Short value) {
            addCriterion("MEMBERCONSUMERID <=", value, "memberconsumerid");
            return (Criteria) this;
        }

        public Criteria andMemberconsumeridIn(List<Short> values) {
            addCriterion("MEMBERCONSUMERID in", values, "memberconsumerid");
            return (Criteria) this;
        }

        public Criteria andMemberconsumeridNotIn(List<Short> values) {
            addCriterion("MEMBERCONSUMERID not in", values, "memberconsumerid");
            return (Criteria) this;
        }

        public Criteria andMemberconsumeridBetween(Short value1, Short value2) {
            addCriterion("MEMBERCONSUMERID between", value1, value2, "memberconsumerid");
            return (Criteria) this;
        }

        public Criteria andMemberconsumeridNotBetween(Short value1, Short value2) {
            addCriterion("MEMBERCONSUMERID not between", value1, value2, "memberconsumerid");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("OPENID is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("OPENID is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("OPENID =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("OPENID <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("OPENID >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("OPENID >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("OPENID <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("OPENID <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("OPENID like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("OPENID not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("OPENID in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("OPENID not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("OPENID between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("OPENID not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyIsNull() {
            addCriterion("CONSUMERMONEY is null");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyIsNotNull() {
            addCriterion("CONSUMERMONEY is not null");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyEqualTo(Short value) {
            addCriterion("CONSUMERMONEY =", value, "consumermoney");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyNotEqualTo(Short value) {
            addCriterion("CONSUMERMONEY <>", value, "consumermoney");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyGreaterThan(Short value) {
            addCriterion("CONSUMERMONEY >", value, "consumermoney");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyGreaterThanOrEqualTo(Short value) {
            addCriterion("CONSUMERMONEY >=", value, "consumermoney");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyLessThan(Short value) {
            addCriterion("CONSUMERMONEY <", value, "consumermoney");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyLessThanOrEqualTo(Short value) {
            addCriterion("CONSUMERMONEY <=", value, "consumermoney");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyIn(List<Short> values) {
            addCriterion("CONSUMERMONEY in", values, "consumermoney");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyNotIn(List<Short> values) {
            addCriterion("CONSUMERMONEY not in", values, "consumermoney");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyBetween(Short value1, Short value2) {
            addCriterion("CONSUMERMONEY between", value1, value2, "consumermoney");
            return (Criteria) this;
        }

        public Criteria andConsumermoneyNotBetween(Short value1, Short value2) {
            addCriterion("CONSUMERMONEY not between", value1, value2, "consumermoney");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreIsNull() {
            addCriterion("DEDUCTIONSCORE is null");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreIsNotNull() {
            addCriterion("DEDUCTIONSCORE is not null");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreEqualTo(Short value) {
            addCriterion("DEDUCTIONSCORE =", value, "deductionscore");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreNotEqualTo(Short value) {
            addCriterion("DEDUCTIONSCORE <>", value, "deductionscore");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreGreaterThan(Short value) {
            addCriterion("DEDUCTIONSCORE >", value, "deductionscore");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreGreaterThanOrEqualTo(Short value) {
            addCriterion("DEDUCTIONSCORE >=", value, "deductionscore");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreLessThan(Short value) {
            addCriterion("DEDUCTIONSCORE <", value, "deductionscore");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreLessThanOrEqualTo(Short value) {
            addCriterion("DEDUCTIONSCORE <=", value, "deductionscore");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreIn(List<Short> values) {
            addCriterion("DEDUCTIONSCORE in", values, "deductionscore");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreNotIn(List<Short> values) {
            addCriterion("DEDUCTIONSCORE not in", values, "deductionscore");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreBetween(Short value1, Short value2) {
            addCriterion("DEDUCTIONSCORE between", value1, value2, "deductionscore");
            return (Criteria) this;
        }

        public Criteria andDeductionscoreNotBetween(Short value1, Short value2) {
            addCriterion("DEDUCTIONSCORE not between", value1, value2, "deductionscore");
            return (Criteria) this;
        }

        public Criteria andFlowNoIsNull() {
            addCriterion("FLOW_NO is null");
            return (Criteria) this;
        }

        public Criteria andFlowNoIsNotNull() {
            addCriterion("FLOW_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFlowNoEqualTo(String value) {
            addCriterion("FLOW_NO =", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoNotEqualTo(String value) {
            addCriterion("FLOW_NO <>", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoGreaterThan(String value) {
            addCriterion("FLOW_NO >", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoGreaterThanOrEqualTo(String value) {
            addCriterion("FLOW_NO >=", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoLessThan(String value) {
            addCriterion("FLOW_NO <", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoLessThanOrEqualTo(String value) {
            addCriterion("FLOW_NO <=", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoLike(String value) {
            addCriterion("FLOW_NO like", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoNotLike(String value) {
            addCriterion("FLOW_NO not like", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoIn(List<String> values) {
            addCriterion("FLOW_NO in", values, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoNotIn(List<String> values) {
            addCriterion("FLOW_NO not in", values, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoBetween(String value1, String value2) {
            addCriterion("FLOW_NO between", value1, value2, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoNotBetween(String value1, String value2) {
            addCriterion("FLOW_NO not between", value1, value2, "flowNo");
            return (Criteria) this;
        }

        public Criteria andBalIsNull() {
            addCriterion("BAL is null");
            return (Criteria) this;
        }

        public Criteria andBalIsNotNull() {
            addCriterion("BAL is not null");
            return (Criteria) this;
        }

        public Criteria andBalEqualTo(String value) {
            addCriterion("BAL =", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalNotEqualTo(String value) {
            addCriterion("BAL <>", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalGreaterThan(String value) {
            addCriterion("BAL >", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalGreaterThanOrEqualTo(String value) {
            addCriterion("BAL >=", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalLessThan(String value) {
            addCriterion("BAL <", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalLessThanOrEqualTo(String value) {
            addCriterion("BAL <=", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalLike(String value) {
            addCriterion("BAL like", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalNotLike(String value) {
            addCriterion("BAL not like", value, "bal");
            return (Criteria) this;
        }

        public Criteria andBalIn(List<String> values) {
            addCriterion("BAL in", values, "bal");
            return (Criteria) this;
        }

        public Criteria andBalNotIn(List<String> values) {
            addCriterion("BAL not in", values, "bal");
            return (Criteria) this;
        }

        public Criteria andBalBetween(String value1, String value2) {
            addCriterion("BAL between", value1, value2, "bal");
            return (Criteria) this;
        }

        public Criteria andBalNotBetween(String value1, String value2) {
            addCriterion("BAL not between", value1, value2, "bal");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andMachTimeIsNull() {
            addCriterion("MACH_TIME is null");
            return (Criteria) this;
        }

        public Criteria andMachTimeIsNotNull() {
            addCriterion("MACH_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andMachTimeEqualTo(String value) {
            addCriterion("MACH_TIME =", value, "machTime");
            return (Criteria) this;
        }

        public Criteria andMachTimeNotEqualTo(String value) {
            addCriterion("MACH_TIME <>", value, "machTime");
            return (Criteria) this;
        }

        public Criteria andMachTimeGreaterThan(String value) {
            addCriterion("MACH_TIME >", value, "machTime");
            return (Criteria) this;
        }

        public Criteria andMachTimeGreaterThanOrEqualTo(String value) {
            addCriterion("MACH_TIME >=", value, "machTime");
            return (Criteria) this;
        }

        public Criteria andMachTimeLessThan(String value) {
            addCriterion("MACH_TIME <", value, "machTime");
            return (Criteria) this;
        }

        public Criteria andMachTimeLessThanOrEqualTo(String value) {
            addCriterion("MACH_TIME <=", value, "machTime");
            return (Criteria) this;
        }

        public Criteria andMachTimeLike(String value) {
            addCriterion("MACH_TIME like", value, "machTime");
            return (Criteria) this;
        }

        public Criteria andMachTimeNotLike(String value) {
            addCriterion("MACH_TIME not like", value, "machTime");
            return (Criteria) this;
        }

        public Criteria andMachTimeIn(List<String> values) {
            addCriterion("MACH_TIME in", values, "machTime");
            return (Criteria) this;
        }

        public Criteria andMachTimeNotIn(List<String> values) {
            addCriterion("MACH_TIME not in", values, "machTime");
            return (Criteria) this;
        }

        public Criteria andMachTimeBetween(String value1, String value2) {
            addCriterion("MACH_TIME between", value1, value2, "machTime");
            return (Criteria) this;
        }

        public Criteria andMachTimeNotBetween(String value1, String value2) {
            addCriterion("MACH_TIME not between", value1, value2, "machTime");
            return (Criteria) this;
        }

        public Criteria andPayWayIsNull() {
            addCriterion("PAY_WAY is null");
            return (Criteria) this;
        }

        public Criteria andPayWayIsNotNull() {
            addCriterion("PAY_WAY is not null");
            return (Criteria) this;
        }

        public Criteria andPayWayEqualTo(String value) {
            addCriterion("PAY_WAY =", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotEqualTo(String value) {
            addCriterion("PAY_WAY <>", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayGreaterThan(String value) {
            addCriterion("PAY_WAY >", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_WAY >=", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayLessThan(String value) {
            addCriterion("PAY_WAY <", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayLessThanOrEqualTo(String value) {
            addCriterion("PAY_WAY <=", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayLike(String value) {
            addCriterion("PAY_WAY like", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotLike(String value) {
            addCriterion("PAY_WAY not like", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayIn(List<String> values) {
            addCriterion("PAY_WAY in", values, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotIn(List<String> values) {
            addCriterion("PAY_WAY not in", values, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayBetween(String value1, String value2) {
            addCriterion("PAY_WAY between", value1, value2, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotBetween(String value1, String value2) {
            addCriterion("PAY_WAY not between", value1, value2, "payWay");
            return (Criteria) this;
        }

        public Criteria andQtyIsNull() {
            addCriterion("QTY is null");
            return (Criteria) this;
        }

        public Criteria andQtyIsNotNull() {
            addCriterion("QTY is not null");
            return (Criteria) this;
        }

        public Criteria andQtyEqualTo(String value) {
            addCriterion("QTY =", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotEqualTo(String value) {
            addCriterion("QTY <>", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThan(String value) {
            addCriterion("QTY >", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThanOrEqualTo(String value) {
            addCriterion("QTY >=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThan(String value) {
            addCriterion("QTY <", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThanOrEqualTo(String value) {
            addCriterion("QTY <=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLike(String value) {
            addCriterion("QTY like", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotLike(String value) {
            addCriterion("QTY not like", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyIn(List<String> values) {
            addCriterion("QTY in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotIn(List<String> values) {
            addCriterion("QTY not in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyBetween(String value1, String value2) {
            addCriterion("QTY between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotBetween(String value1, String value2) {
            addCriterion("QTY not between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(String value) {
            addCriterion("PRICE =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(String value) {
            addCriterion("PRICE <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(String value) {
            addCriterion("PRICE >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(String value) {
            addCriterion("PRICE >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(String value) {
            addCriterion("PRICE <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(String value) {
            addCriterion("PRICE <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLike(String value) {
            addCriterion("PRICE like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotLike(String value) {
            addCriterion("PRICE not like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<String> values) {
            addCriterion("PRICE in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<String> values) {
            addCriterion("PRICE not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(String value1, String value2) {
            addCriterion("PRICE between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(String value1, String value2) {
            addCriterion("PRICE not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andOilNameIsNull() {
            addCriterion("OIL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOilNameIsNotNull() {
            addCriterion("OIL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOilNameEqualTo(String value) {
            addCriterion("OIL_NAME =", value, "oilName");
            return (Criteria) this;
        }

        public Criteria andOilNameNotEqualTo(String value) {
            addCriterion("OIL_NAME <>", value, "oilName");
            return (Criteria) this;
        }

        public Criteria andOilNameGreaterThan(String value) {
            addCriterion("OIL_NAME >", value, "oilName");
            return (Criteria) this;
        }

        public Criteria andOilNameGreaterThanOrEqualTo(String value) {
            addCriterion("OIL_NAME >=", value, "oilName");
            return (Criteria) this;
        }

        public Criteria andOilNameLessThan(String value) {
            addCriterion("OIL_NAME <", value, "oilName");
            return (Criteria) this;
        }

        public Criteria andOilNameLessThanOrEqualTo(String value) {
            addCriterion("OIL_NAME <=", value, "oilName");
            return (Criteria) this;
        }

        public Criteria andOilNameLike(String value) {
            addCriterion("OIL_NAME like", value, "oilName");
            return (Criteria) this;
        }

        public Criteria andOilNameNotLike(String value) {
            addCriterion("OIL_NAME not like", value, "oilName");
            return (Criteria) this;
        }

        public Criteria andOilNameIn(List<String> values) {
            addCriterion("OIL_NAME in", values, "oilName");
            return (Criteria) this;
        }

        public Criteria andOilNameNotIn(List<String> values) {
            addCriterion("OIL_NAME not in", values, "oilName");
            return (Criteria) this;
        }

        public Criteria andOilNameBetween(String value1, String value2) {
            addCriterion("OIL_NAME between", value1, value2, "oilName");
            return (Criteria) this;
        }

        public Criteria andOilNameNotBetween(String value1, String value2) {
            addCriterion("OIL_NAME not between", value1, value2, "oilName");
            return (Criteria) this;
        }

        public Criteria andStNameIsNull() {
            addCriterion("ST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andStNameIsNotNull() {
            addCriterion("ST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andStNameEqualTo(String value) {
            addCriterion("ST_NAME =", value, "stName");
            return (Criteria) this;
        }

        public Criteria andStNameNotEqualTo(String value) {
            addCriterion("ST_NAME <>", value, "stName");
            return (Criteria) this;
        }

        public Criteria andStNameGreaterThan(String value) {
            addCriterion("ST_NAME >", value, "stName");
            return (Criteria) this;
        }

        public Criteria andStNameGreaterThanOrEqualTo(String value) {
            addCriterion("ST_NAME >=", value, "stName");
            return (Criteria) this;
        }

        public Criteria andStNameLessThan(String value) {
            addCriterion("ST_NAME <", value, "stName");
            return (Criteria) this;
        }

        public Criteria andStNameLessThanOrEqualTo(String value) {
            addCriterion("ST_NAME <=", value, "stName");
            return (Criteria) this;
        }

        public Criteria andStNameLike(String value) {
            addCriterion("ST_NAME like", value, "stName");
            return (Criteria) this;
        }

        public Criteria andStNameNotLike(String value) {
            addCriterion("ST_NAME not like", value, "stName");
            return (Criteria) this;
        }

        public Criteria andStNameIn(List<String> values) {
            addCriterion("ST_NAME in", values, "stName");
            return (Criteria) this;
        }

        public Criteria andStNameNotIn(List<String> values) {
            addCriterion("ST_NAME not in", values, "stName");
            return (Criteria) this;
        }

        public Criteria andStNameBetween(String value1, String value2) {
            addCriterion("ST_NAME between", value1, value2, "stName");
            return (Criteria) this;
        }

        public Criteria andStNameNotBetween(String value1, String value2) {
            addCriterion("ST_NAME not between", value1, value2, "stName");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("DELETEFLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("DELETEFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagEqualTo(String value) {
            addCriterion("DELETEFLAG =", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotEqualTo(String value) {
            addCriterion("DELETEFLAG <>", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThan(String value) {
            addCriterion("DELETEFLAG >", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETEFLAG >=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThan(String value) {
            addCriterion("DELETEFLAG <", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(String value) {
            addCriterion("DELETEFLAG <=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLike(String value) {
            addCriterion("DELETEFLAG like", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotLike(String value) {
            addCriterion("DELETEFLAG not like", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIn(List<String> values) {
            addCriterion("DELETEFLAG in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotIn(List<String> values) {
            addCriterion("DELETEFLAG not in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagBetween(String value1, String value2) {
            addCriterion("DELETEFLAG between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotBetween(String value1, String value2) {
            addCriterion("DELETEFLAG not between", value1, value2, "deleteflag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 09 15:34:13 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_CONSUMER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}