package com.tianniu.pojo;

import java.util.Date;

public class MemberGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_GOODS.GOODID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String goodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_GOODS.GOODPRODUCTID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String goodproductid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_GOODS.GOODNAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String goodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_GOODS.GOODREFERRED
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String goodreferred;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_GOODS.GOODNUMBER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String goodnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_GOODS.GOODMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String goodmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_GOODS.GOODSCORE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String goodscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_GOODS.GOODBEGINTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private Date goodbegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_GOODS.GOODENDTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private Date goodendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_GOODS.GOODOVERDUE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String goodoverdue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_GOODS.GOODID
     *
     * @return the value of MEMBER_GOODS.GOODID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_GOODS.GOODID
     *
     * @param goodid the value for MEMBER_GOODS.GOODID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setGoodid(String goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_GOODS.GOODPRODUCTID
     *
     * @return the value of MEMBER_GOODS.GOODPRODUCTID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getGoodproductid() {
        return goodproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_GOODS.GOODPRODUCTID
     *
     * @param goodproductid the value for MEMBER_GOODS.GOODPRODUCTID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setGoodproductid(String goodproductid) {
        this.goodproductid = goodproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_GOODS.GOODNAME
     *
     * @return the value of MEMBER_GOODS.GOODNAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getGoodname() {
        return goodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_GOODS.GOODNAME
     *
     * @param goodname the value for MEMBER_GOODS.GOODNAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setGoodname(String goodname) {
        this.goodname = goodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_GOODS.GOODREFERRED
     *
     * @return the value of MEMBER_GOODS.GOODREFERRED
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getGoodreferred() {
        return goodreferred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_GOODS.GOODREFERRED
     *
     * @param goodreferred the value for MEMBER_GOODS.GOODREFERRED
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setGoodreferred(String goodreferred) {
        this.goodreferred = goodreferred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_GOODS.GOODNUMBER
     *
     * @return the value of MEMBER_GOODS.GOODNUMBER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getGoodnumber() {
        return goodnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_GOODS.GOODNUMBER
     *
     * @param goodnumber the value for MEMBER_GOODS.GOODNUMBER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setGoodnumber(String goodnumber) {
        this.goodnumber = goodnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_GOODS.GOODMONEY
     *
     * @return the value of MEMBER_GOODS.GOODMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getGoodmoney() {
        return goodmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_GOODS.GOODMONEY
     *
     * @param goodmoney the value for MEMBER_GOODS.GOODMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setGoodmoney(String goodmoney) {
        this.goodmoney = goodmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_GOODS.GOODSCORE
     *
     * @return the value of MEMBER_GOODS.GOODSCORE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getGoodscore() {
        return goodscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_GOODS.GOODSCORE
     *
     * @param goodscore the value for MEMBER_GOODS.GOODSCORE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setGoodscore(String goodscore) {
        this.goodscore = goodscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_GOODS.GOODBEGINTIME
     *
     * @return the value of MEMBER_GOODS.GOODBEGINTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Date getGoodbegintime() {
        return goodbegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_GOODS.GOODBEGINTIME
     *
     * @param goodbegintime the value for MEMBER_GOODS.GOODBEGINTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setGoodbegintime(Date goodbegintime) {
        this.goodbegintime = goodbegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_GOODS.GOODENDTIME
     *
     * @return the value of MEMBER_GOODS.GOODENDTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Date getGoodendtime() {
        return goodendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_GOODS.GOODENDTIME
     *
     * @param goodendtime the value for MEMBER_GOODS.GOODENDTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setGoodendtime(Date goodendtime) {
        this.goodendtime = goodendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_GOODS.GOODOVERDUE
     *
     * @return the value of MEMBER_GOODS.GOODOVERDUE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getGoodoverdue() {
        return goodoverdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_GOODS.GOODOVERDUE
     *
     * @param goodoverdue the value for MEMBER_GOODS.GOODOVERDUE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setGoodoverdue(String goodoverdue) {
        this.goodoverdue = goodoverdue;
    }
}