package com.tianniu.pojo;

public class MemberInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_INFO.MEMBERINFOID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private Short memberinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_INFO.OPENID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_INFO.SCORE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private Short score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_INFO.MEMBERLEVEL
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private Short memberlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_INFO.MEMBERMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private Short membermoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_INFO.OLDMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private Short oldmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_INFO.TIANNIU02
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String tianniu02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_INFO.TIANNIU03
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String tianniu03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_INFO.TIANNIU04
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String tianniu04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_INFO.REMARKS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_INFO.MEMBERINFOID
     *
     * @return the value of MEMBER_INFO.MEMBERINFOID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getMemberinfoid() {
        return memberinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_INFO.MEMBERINFOID
     *
     * @param memberinfoid the value for MEMBER_INFO.MEMBERINFOID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setMemberinfoid(Short memberinfoid) {
        this.memberinfoid = memberinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_INFO.OPENID
     *
     * @return the value of MEMBER_INFO.OPENID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_INFO.OPENID
     *
     * @param openid the value for MEMBER_INFO.OPENID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_INFO.SCORE
     *
     * @return the value of MEMBER_INFO.SCORE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_INFO.SCORE
     *
     * @param score the value for MEMBER_INFO.SCORE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setScore(Short score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_INFO.MEMBERLEVEL
     *
     * @return the value of MEMBER_INFO.MEMBERLEVEL
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getMemberlevel() {
        return memberlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_INFO.MEMBERLEVEL
     *
     * @param memberlevel the value for MEMBER_INFO.MEMBERLEVEL
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setMemberlevel(Short memberlevel) {
        this.memberlevel = memberlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_INFO.MEMBERMONEY
     *
     * @return the value of MEMBER_INFO.MEMBERMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getMembermoney() {
        return membermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_INFO.MEMBERMONEY
     *
     * @param membermoney the value for MEMBER_INFO.MEMBERMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setMembermoney(Short membermoney) {
        this.membermoney = membermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_INFO.OLDMONEY
     *
     * @return the value of MEMBER_INFO.OLDMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getOldmoney() {
        return oldmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_INFO.OLDMONEY
     *
     * @param oldmoney the value for MEMBER_INFO.OLDMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setOldmoney(Short oldmoney) {
        this.oldmoney = oldmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_INFO.TIANNIU02
     *
     * @return the value of MEMBER_INFO.TIANNIU02
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getTianniu02() {
        return tianniu02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_INFO.TIANNIU02
     *
     * @param tianniu02 the value for MEMBER_INFO.TIANNIU02
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setTianniu02(String tianniu02) {
        this.tianniu02 = tianniu02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_INFO.TIANNIU03
     *
     * @return the value of MEMBER_INFO.TIANNIU03
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getTianniu03() {
        return tianniu03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_INFO.TIANNIU03
     *
     * @param tianniu03 the value for MEMBER_INFO.TIANNIU03
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setTianniu03(String tianniu03) {
        this.tianniu03 = tianniu03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_INFO.TIANNIU04
     *
     * @return the value of MEMBER_INFO.TIANNIU04
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getTianniu04() {
        return tianniu04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_INFO.TIANNIU04
     *
     * @param tianniu04 the value for MEMBER_INFO.TIANNIU04
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setTianniu04(String tianniu04) {
        this.tianniu04 = tianniu04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_INFO.REMARKS
     *
     * @return the value of MEMBER_INFO.REMARKS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_INFO.REMARKS
     *
     * @param remarks the value for MEMBER_INFO.REMARKS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}