package com.tianniu.pojo;

import java.util.ArrayList;
import java.util.List;

public class MemberUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    public MemberUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOpenidIsNull() {
            addCriterion("OPENID is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("OPENID is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("OPENID =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("OPENID <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("OPENID >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("OPENID >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("OPENID <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("OPENID <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("OPENID like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("OPENID not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("OPENID in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("OPENID not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("OPENID between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("OPENID not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andMemberidIsNull() {
            addCriterion("MEMBERID is null");
            return (Criteria) this;
        }

        public Criteria andMemberidIsNotNull() {
            addCriterion("MEMBERID is not null");
            return (Criteria) this;
        }

        public Criteria andMemberidEqualTo(Short value) {
            addCriterion("MEMBERID =", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidNotEqualTo(Short value) {
            addCriterion("MEMBERID <>", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidGreaterThan(Short value) {
            addCriterion("MEMBERID >", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidGreaterThanOrEqualTo(Short value) {
            addCriterion("MEMBERID >=", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidLessThan(Short value) {
            addCriterion("MEMBERID <", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidLessThanOrEqualTo(Short value) {
            addCriterion("MEMBERID <=", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidIn(List<Short> values) {
            addCriterion("MEMBERID in", values, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidNotIn(List<Short> values) {
            addCriterion("MEMBERID not in", values, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidBetween(Short value1, Short value2) {
            addCriterion("MEMBERID between", value1, value2, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidNotBetween(Short value1, Short value2) {
            addCriterion("MEMBERID not between", value1, value2, "memberid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("SEX in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("SEX not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("AGE is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("AGE is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Short value) {
            addCriterion("AGE =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Short value) {
            addCriterion("AGE <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Short value) {
            addCriterion("AGE >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Short value) {
            addCriterion("AGE >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Short value) {
            addCriterion("AGE <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Short value) {
            addCriterion("AGE <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Short> values) {
            addCriterion("AGE in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Short> values) {
            addCriterion("AGE not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Short value1, Short value2) {
            addCriterion("AGE between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Short value1, Short value2) {
            addCriterion("AGE not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andSfzhIsNull() {
            addCriterion("SFZH is null");
            return (Criteria) this;
        }

        public Criteria andSfzhIsNotNull() {
            addCriterion("SFZH is not null");
            return (Criteria) this;
        }

        public Criteria andSfzhEqualTo(String value) {
            addCriterion("SFZH =", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotEqualTo(String value) {
            addCriterion("SFZH <>", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhGreaterThan(String value) {
            addCriterion("SFZH >", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhGreaterThanOrEqualTo(String value) {
            addCriterion("SFZH >=", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhLessThan(String value) {
            addCriterion("SFZH <", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhLessThanOrEqualTo(String value) {
            addCriterion("SFZH <=", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhLike(String value) {
            addCriterion("SFZH like", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotLike(String value) {
            addCriterion("SFZH not like", value, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhIn(List<String> values) {
            addCriterion("SFZH in", values, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotIn(List<String> values) {
            addCriterion("SFZH not in", values, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhBetween(String value1, String value2) {
            addCriterion("SFZH between", value1, value2, "sfzh");
            return (Criteria) this;
        }

        public Criteria andSfzhNotBetween(String value1, String value2) {
            addCriterion("SFZH not between", value1, value2, "sfzh");
            return (Criteria) this;
        }

        public Criteria andCardNumberIsNull() {
            addCriterion("CARD_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andCardNumberIsNotNull() {
            addCriterion("CARD_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andCardNumberEqualTo(String value) {
            addCriterion("CARD_NUMBER =", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotEqualTo(String value) {
            addCriterion("CARD_NUMBER <>", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberGreaterThan(String value) {
            addCriterion("CARD_NUMBER >", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER >=", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberLessThan(String value) {
            addCriterion("CARD_NUMBER <", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberLessThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER <=", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberLike(String value) {
            addCriterion("CARD_NUMBER like", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotLike(String value) {
            addCriterion("CARD_NUMBER not like", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberIn(List<String> values) {
            addCriterion("CARD_NUMBER in", values, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotIn(List<String> values) {
            addCriterion("CARD_NUMBER not in", values, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER between", value1, value2, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER not between", value1, value2, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("PHONE is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(Short value) {
            addCriterion("PHONE =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(Short value) {
            addCriterion("PHONE <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(Short value) {
            addCriterion("PHONE >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(Short value) {
            addCriterion("PHONE >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(Short value) {
            addCriterion("PHONE <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(Short value) {
            addCriterion("PHONE <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<Short> values) {
            addCriterion("PHONE in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<Short> values) {
            addCriterion("PHONE not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(Short value1, Short value2) {
            addCriterion("PHONE between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(Short value1, Short value2) {
            addCriterion("PHONE not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andCarCdIsNull() {
            addCriterion("CAR_CD is null");
            return (Criteria) this;
        }

        public Criteria andCarCdIsNotNull() {
            addCriterion("CAR_CD is not null");
            return (Criteria) this;
        }

        public Criteria andCarCdEqualTo(String value) {
            addCriterion("CAR_CD =", value, "carCd");
            return (Criteria) this;
        }

        public Criteria andCarCdNotEqualTo(String value) {
            addCriterion("CAR_CD <>", value, "carCd");
            return (Criteria) this;
        }

        public Criteria andCarCdGreaterThan(String value) {
            addCriterion("CAR_CD >", value, "carCd");
            return (Criteria) this;
        }

        public Criteria andCarCdGreaterThanOrEqualTo(String value) {
            addCriterion("CAR_CD >=", value, "carCd");
            return (Criteria) this;
        }

        public Criteria andCarCdLessThan(String value) {
            addCriterion("CAR_CD <", value, "carCd");
            return (Criteria) this;
        }

        public Criteria andCarCdLessThanOrEqualTo(String value) {
            addCriterion("CAR_CD <=", value, "carCd");
            return (Criteria) this;
        }

        public Criteria andCarCdLike(String value) {
            addCriterion("CAR_CD like", value, "carCd");
            return (Criteria) this;
        }

        public Criteria andCarCdNotLike(String value) {
            addCriterion("CAR_CD not like", value, "carCd");
            return (Criteria) this;
        }

        public Criteria andCarCdIn(List<String> values) {
            addCriterion("CAR_CD in", values, "carCd");
            return (Criteria) this;
        }

        public Criteria andCarCdNotIn(List<String> values) {
            addCriterion("CAR_CD not in", values, "carCd");
            return (Criteria) this;
        }

        public Criteria andCarCdBetween(String value1, String value2) {
            addCriterion("CAR_CD between", value1, value2, "carCd");
            return (Criteria) this;
        }

        public Criteria andCarCdNotBetween(String value1, String value2) {
            addCriterion("CAR_CD not between", value1, value2, "carCd");
            return (Criteria) this;
        }

        public Criteria andCardflagIsNull() {
            addCriterion("CARDFLAG is null");
            return (Criteria) this;
        }

        public Criteria andCardflagIsNotNull() {
            addCriterion("CARDFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andCardflagEqualTo(String value) {
            addCriterion("CARDFLAG =", value, "cardflag");
            return (Criteria) this;
        }

        public Criteria andCardflagNotEqualTo(String value) {
            addCriterion("CARDFLAG <>", value, "cardflag");
            return (Criteria) this;
        }

        public Criteria andCardflagGreaterThan(String value) {
            addCriterion("CARDFLAG >", value, "cardflag");
            return (Criteria) this;
        }

        public Criteria andCardflagGreaterThanOrEqualTo(String value) {
            addCriterion("CARDFLAG >=", value, "cardflag");
            return (Criteria) this;
        }

        public Criteria andCardflagLessThan(String value) {
            addCriterion("CARDFLAG <", value, "cardflag");
            return (Criteria) this;
        }

        public Criteria andCardflagLessThanOrEqualTo(String value) {
            addCriterion("CARDFLAG <=", value, "cardflag");
            return (Criteria) this;
        }

        public Criteria andCardflagLike(String value) {
            addCriterion("CARDFLAG like", value, "cardflag");
            return (Criteria) this;
        }

        public Criteria andCardflagNotLike(String value) {
            addCriterion("CARDFLAG not like", value, "cardflag");
            return (Criteria) this;
        }

        public Criteria andCardflagIn(List<String> values) {
            addCriterion("CARDFLAG in", values, "cardflag");
            return (Criteria) this;
        }

        public Criteria andCardflagNotIn(List<String> values) {
            addCriterion("CARDFLAG not in", values, "cardflag");
            return (Criteria) this;
        }

        public Criteria andCardflagBetween(String value1, String value2) {
            addCriterion("CARDFLAG between", value1, value2, "cardflag");
            return (Criteria) this;
        }

        public Criteria andCardflagNotBetween(String value1, String value2) {
            addCriterion("CARDFLAG not between", value1, value2, "cardflag");
            return (Criteria) this;
        }

        public Criteria andTianniu02IsNull() {
            addCriterion("TIANNIU02 is null");
            return (Criteria) this;
        }

        public Criteria andTianniu02IsNotNull() {
            addCriterion("TIANNIU02 is not null");
            return (Criteria) this;
        }

        public Criteria andTianniu02EqualTo(String value) {
            addCriterion("TIANNIU02 =", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02NotEqualTo(String value) {
            addCriterion("TIANNIU02 <>", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02GreaterThan(String value) {
            addCriterion("TIANNIU02 >", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02GreaterThanOrEqualTo(String value) {
            addCriterion("TIANNIU02 >=", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02LessThan(String value) {
            addCriterion("TIANNIU02 <", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02LessThanOrEqualTo(String value) {
            addCriterion("TIANNIU02 <=", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02Like(String value) {
            addCriterion("TIANNIU02 like", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02NotLike(String value) {
            addCriterion("TIANNIU02 not like", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02In(List<String> values) {
            addCriterion("TIANNIU02 in", values, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02NotIn(List<String> values) {
            addCriterion("TIANNIU02 not in", values, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02Between(String value1, String value2) {
            addCriterion("TIANNIU02 between", value1, value2, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02NotBetween(String value1, String value2) {
            addCriterion("TIANNIU02 not between", value1, value2, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu03IsNull() {
            addCriterion("TIANNIU03 is null");
            return (Criteria) this;
        }

        public Criteria andTianniu03IsNotNull() {
            addCriterion("TIANNIU03 is not null");
            return (Criteria) this;
        }

        public Criteria andTianniu03EqualTo(String value) {
            addCriterion("TIANNIU03 =", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03NotEqualTo(String value) {
            addCriterion("TIANNIU03 <>", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03GreaterThan(String value) {
            addCriterion("TIANNIU03 >", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03GreaterThanOrEqualTo(String value) {
            addCriterion("TIANNIU03 >=", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03LessThan(String value) {
            addCriterion("TIANNIU03 <", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03LessThanOrEqualTo(String value) {
            addCriterion("TIANNIU03 <=", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03Like(String value) {
            addCriterion("TIANNIU03 like", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03NotLike(String value) {
            addCriterion("TIANNIU03 not like", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03In(List<String> values) {
            addCriterion("TIANNIU03 in", values, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03NotIn(List<String> values) {
            addCriterion("TIANNIU03 not in", values, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03Between(String value1, String value2) {
            addCriterion("TIANNIU03 between", value1, value2, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03NotBetween(String value1, String value2) {
            addCriterion("TIANNIU03 not between", value1, value2, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu04IsNull() {
            addCriterion("TIANNIU04 is null");
            return (Criteria) this;
        }

        public Criteria andTianniu04IsNotNull() {
            addCriterion("TIANNIU04 is not null");
            return (Criteria) this;
        }

        public Criteria andTianniu04EqualTo(String value) {
            addCriterion("TIANNIU04 =", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04NotEqualTo(String value) {
            addCriterion("TIANNIU04 <>", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04GreaterThan(String value) {
            addCriterion("TIANNIU04 >", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04GreaterThanOrEqualTo(String value) {
            addCriterion("TIANNIU04 >=", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04LessThan(String value) {
            addCriterion("TIANNIU04 <", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04LessThanOrEqualTo(String value) {
            addCriterion("TIANNIU04 <=", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04Like(String value) {
            addCriterion("TIANNIU04 like", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04NotLike(String value) {
            addCriterion("TIANNIU04 not like", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04In(List<String> values) {
            addCriterion("TIANNIU04 in", values, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04NotIn(List<String> values) {
            addCriterion("TIANNIU04 not in", values, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04Between(String value1, String value2) {
            addCriterion("TIANNIU04 between", value1, value2, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04NotBetween(String value1, String value2) {
            addCriterion("TIANNIU04 not between", value1, value2, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("MONEY is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("MONEY is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(String value) {
            addCriterion("MONEY =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(String value) {
            addCriterion("MONEY <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(String value) {
            addCriterion("MONEY >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("MONEY >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(String value) {
            addCriterion("MONEY <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(String value) {
            addCriterion("MONEY <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLike(String value) {
            addCriterion("MONEY like", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotLike(String value) {
            addCriterion("MONEY not like", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<String> values) {
            addCriterion("MONEY in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<String> values) {
            addCriterion("MONEY not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(String value1, String value2) {
            addCriterion("MONEY between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(String value1, String value2) {
            addCriterion("MONEY not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("DELETEFLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("DELETEFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagEqualTo(String value) {
            addCriterion("DELETEFLAG =", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotEqualTo(String value) {
            addCriterion("DELETEFLAG <>", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThan(String value) {
            addCriterion("DELETEFLAG >", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETEFLAG >=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThan(String value) {
            addCriterion("DELETEFLAG <", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(String value) {
            addCriterion("DELETEFLAG <=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLike(String value) {
            addCriterion("DELETEFLAG like", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotLike(String value) {
            addCriterion("DELETEFLAG not like", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIn(List<String> values) {
            addCriterion("DELETEFLAG in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotIn(List<String> values) {
            addCriterion("DELETEFLAG not in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagBetween(String value1, String value2) {
            addCriterion("DELETEFLAG between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotBetween(String value1, String value2) {
            addCriterion("DELETEFLAG not between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andRechargeIsNull() {
            addCriterion("RECHARGE is null");
            return (Criteria) this;
        }

        public Criteria andRechargeIsNotNull() {
            addCriterion("RECHARGE is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeEqualTo(Short value) {
            addCriterion("RECHARGE =", value, "recharge");
            return (Criteria) this;
        }

        public Criteria andRechargeNotEqualTo(Short value) {
            addCriterion("RECHARGE <>", value, "recharge");
            return (Criteria) this;
        }

        public Criteria andRechargeGreaterThan(Short value) {
            addCriterion("RECHARGE >", value, "recharge");
            return (Criteria) this;
        }

        public Criteria andRechargeGreaterThanOrEqualTo(Short value) {
            addCriterion("RECHARGE >=", value, "recharge");
            return (Criteria) this;
        }

        public Criteria andRechargeLessThan(Short value) {
            addCriterion("RECHARGE <", value, "recharge");
            return (Criteria) this;
        }

        public Criteria andRechargeLessThanOrEqualTo(Short value) {
            addCriterion("RECHARGE <=", value, "recharge");
            return (Criteria) this;
        }

        public Criteria andRechargeIn(List<Short> values) {
            addCriterion("RECHARGE in", values, "recharge");
            return (Criteria) this;
        }

        public Criteria andRechargeNotIn(List<Short> values) {
            addCriterion("RECHARGE not in", values, "recharge");
            return (Criteria) this;
        }

        public Criteria andRechargeBetween(Short value1, Short value2) {
            addCriterion("RECHARGE between", value1, value2, "recharge");
            return (Criteria) this;
        }

        public Criteria andRechargeNotBetween(Short value1, Short value2) {
            addCriterion("RECHARGE not between", value1, value2, "recharge");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeIsNull() {
            addCriterion("CARDBINDINGTIME is null");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeIsNotNull() {
            addCriterion("CARDBINDINGTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeEqualTo(String value) {
            addCriterion("CARDBINDINGTIME =", value, "cardbindingtime");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeNotEqualTo(String value) {
            addCriterion("CARDBINDINGTIME <>", value, "cardbindingtime");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeGreaterThan(String value) {
            addCriterion("CARDBINDINGTIME >", value, "cardbindingtime");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeGreaterThanOrEqualTo(String value) {
            addCriterion("CARDBINDINGTIME >=", value, "cardbindingtime");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeLessThan(String value) {
            addCriterion("CARDBINDINGTIME <", value, "cardbindingtime");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeLessThanOrEqualTo(String value) {
            addCriterion("CARDBINDINGTIME <=", value, "cardbindingtime");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeLike(String value) {
            addCriterion("CARDBINDINGTIME like", value, "cardbindingtime");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeNotLike(String value) {
            addCriterion("CARDBINDINGTIME not like", value, "cardbindingtime");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeIn(List<String> values) {
            addCriterion("CARDBINDINGTIME in", values, "cardbindingtime");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeNotIn(List<String> values) {
            addCriterion("CARDBINDINGTIME not in", values, "cardbindingtime");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeBetween(String value1, String value2) {
            addCriterion("CARDBINDINGTIME between", value1, value2, "cardbindingtime");
            return (Criteria) this;
        }

        public Criteria andCardbindingtimeNotBetween(String value1, String value2) {
            addCriterion("CARDBINDINGTIME not between", value1, value2, "cardbindingtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_USER
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 09 15:15:06 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_USER
     *
     * @mbggenerated Wed Jan 09 15:15:06 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}