package com.tianniu.pojo;

public class MemberOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_ORDER.ORDERNUMBER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String ordernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_ORDER.CARD_NUMBER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private Short cardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_ORDER.ORDERTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_ORDER.SUCCESSFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String successflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_ORDER.FAILFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String failflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_ORDER.ORDERNUMBER
     *
     * @return the value of MEMBER_ORDER.ORDERNUMBER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_ORDER.ORDERNUMBER
     *
     * @param ordernumber the value for MEMBER_ORDER.ORDERNUMBER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_ORDER.CARD_NUMBER
     *
     * @return the value of MEMBER_ORDER.CARD_NUMBER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_ORDER.CARD_NUMBER
     *
     * @param cardNumber the value for MEMBER_ORDER.CARD_NUMBER
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setCardNumber(Short cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_ORDER.ORDERTIME
     *
     * @return the value of MEMBER_ORDER.ORDERTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_ORDER.ORDERTIME
     *
     * @param ordertime the value for MEMBER_ORDER.ORDERTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setOrdertime(String ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_ORDER.SUCCESSFLAG
     *
     * @return the value of MEMBER_ORDER.SUCCESSFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getSuccessflag() {
        return successflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_ORDER.SUCCESSFLAG
     *
     * @param successflag the value for MEMBER_ORDER.SUCCESSFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setSuccessflag(String successflag) {
        this.successflag = successflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_ORDER.FAILFLAG
     *
     * @return the value of MEMBER_ORDER.FAILFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getFailflag() {
        return failflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_ORDER.FAILFLAG
     *
     * @param failflag the value for MEMBER_ORDER.FAILFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setFailflag(String failflag) {
        this.failflag = failflag;
    }
}