package com.tianniu.pojo;

public class MemberConsumer {
    private Short memberconsumerid;
    private String openid;
    private Short consumermoney;
    private Short deductionscore;
    private String flowNo;
    private String bal;
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_CONSUMER.MACH_TIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String machTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_CONSUMER.PAY_WAY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_CONSUMER.QTY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_CONSUMER.PRICE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_CONSUMER.OIL_NAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String oilName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_CONSUMER.ST_NAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String stName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_CONSUMER.DELETEFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.MEMBERCONSUMERID
     *
     * @return the value of MEMBER_CONSUMER.MEMBERCONSUMERID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getMemberconsumerid() {
        return memberconsumerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.MEMBERCONSUMERID
     *
     * @param memberconsumerid the value for MEMBER_CONSUMER.MEMBERCONSUMERID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setMemberconsumerid(Short memberconsumerid) {
        this.memberconsumerid = memberconsumerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.OPENID
     *
     * @return the value of MEMBER_CONSUMER.OPENID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.OPENID
     *
     * @param openid the value for MEMBER_CONSUMER.OPENID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.CONSUMERMONEY
     *
     * @return the value of MEMBER_CONSUMER.CONSUMERMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getConsumermoney() {
        return consumermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.CONSUMERMONEY
     *
     * @param consumermoney the value for MEMBER_CONSUMER.CONSUMERMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setConsumermoney(Short consumermoney) {
        this.consumermoney = consumermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.DEDUCTIONSCORE
     *
     * @return the value of MEMBER_CONSUMER.DEDUCTIONSCORE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getDeductionscore() {
        return deductionscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.DEDUCTIONSCORE
     *
     * @param deductionscore the value for MEMBER_CONSUMER.DEDUCTIONSCORE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setDeductionscore(Short deductionscore) {
        this.deductionscore = deductionscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.FLOW_NO
     *
     * @return the value of MEMBER_CONSUMER.FLOW_NO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.FLOW_NO
     *
     * @param flowNo the value for MEMBER_CONSUMER.FLOW_NO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.BAL
     *
     * @return the value of MEMBER_CONSUMER.BAL
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getBal() {
        return bal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.BAL
     *
     * @param bal the value for MEMBER_CONSUMER.BAL
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setBal(String bal) {
        this.bal = bal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.REMARKS
     *
     * @return the value of MEMBER_CONSUMER.REMARKS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.REMARKS
     *
     * @param remarks the value for MEMBER_CONSUMER.REMARKS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.MACH_TIME
     *
     * @return the value of MEMBER_CONSUMER.MACH_TIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getMachTime() {
        return machTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.MACH_TIME
     *
     * @param machTime the value for MEMBER_CONSUMER.MACH_TIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setMachTime(String machTime) {
        this.machTime = machTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.PAY_WAY
     *
     * @return the value of MEMBER_CONSUMER.PAY_WAY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.PAY_WAY
     *
     * @param payWay the value for MEMBER_CONSUMER.PAY_WAY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.QTY
     *
     * @return the value of MEMBER_CONSUMER.QTY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.QTY
     *
     * @param qty the value for MEMBER_CONSUMER.QTY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setQty(String qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.PRICE
     *
     * @return the value of MEMBER_CONSUMER.PRICE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.PRICE
     *
     * @param price the value for MEMBER_CONSUMER.PRICE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.OIL_NAME
     *
     * @return the value of MEMBER_CONSUMER.OIL_NAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getOilName() {
        return oilName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.OIL_NAME
     *
     * @param oilName the value for MEMBER_CONSUMER.OIL_NAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setOilName(String oilName) {
        this.oilName = oilName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.ST_NAME
     *
     * @return the value of MEMBER_CONSUMER.ST_NAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getStName() {
        return stName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.ST_NAME
     *
     * @param stName the value for MEMBER_CONSUMER.ST_NAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setStName(String stName) {
        this.stName = stName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CONSUMER.DELETEFLAG
     *
     * @return the value of MEMBER_CONSUMER.DELETEFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CONSUMER.DELETEFLAG
     *
     * @param deleteflag the value for MEMBER_CONSUMER.DELETEFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

	@Override
	public String toString() {
		return "MemberConsumer [memberconsumerid=" + memberconsumerid + ", openid=" + openid + ", consumermoney="
				+ consumermoney + ", deductionscore=" + deductionscore + ", flowNo=" + flowNo + ", bal=" + bal
				+ ", remarks=" + remarks + ", machTime=" + machTime + ", payWay=" + payWay + ", qty=" + qty + ", price="
				+ price + ", oilName=" + oilName + ", stName=" + stName + ", deleteflag=" + deleteflag + "]";
	}
    
}