package com.tianniu.pojo;

import java.util.ArrayList;
import java.util.List;

public class MemberInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public MemberInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMemberinfoidIsNull() {
            addCriterion("MEMBERINFOID is null");
            return (Criteria) this;
        }

        public Criteria andMemberinfoidIsNotNull() {
            addCriterion("MEMBERINFOID is not null");
            return (Criteria) this;
        }

        public Criteria andMemberinfoidEqualTo(Short value) {
            addCriterion("MEMBERINFOID =", value, "memberinfoid");
            return (Criteria) this;
        }

        public Criteria andMemberinfoidNotEqualTo(Short value) {
            addCriterion("MEMBERINFOID <>", value, "memberinfoid");
            return (Criteria) this;
        }

        public Criteria andMemberinfoidGreaterThan(Short value) {
            addCriterion("MEMBERINFOID >", value, "memberinfoid");
            return (Criteria) this;
        }

        public Criteria andMemberinfoidGreaterThanOrEqualTo(Short value) {
            addCriterion("MEMBERINFOID >=", value, "memberinfoid");
            return (Criteria) this;
        }

        public Criteria andMemberinfoidLessThan(Short value) {
            addCriterion("MEMBERINFOID <", value, "memberinfoid");
            return (Criteria) this;
        }

        public Criteria andMemberinfoidLessThanOrEqualTo(Short value) {
            addCriterion("MEMBERINFOID <=", value, "memberinfoid");
            return (Criteria) this;
        }

        public Criteria andMemberinfoidIn(List<Short> values) {
            addCriterion("MEMBERINFOID in", values, "memberinfoid");
            return (Criteria) this;
        }

        public Criteria andMemberinfoidNotIn(List<Short> values) {
            addCriterion("MEMBERINFOID not in", values, "memberinfoid");
            return (Criteria) this;
        }

        public Criteria andMemberinfoidBetween(Short value1, Short value2) {
            addCriterion("MEMBERINFOID between", value1, value2, "memberinfoid");
            return (Criteria) this;
        }

        public Criteria andMemberinfoidNotBetween(Short value1, Short value2) {
            addCriterion("MEMBERINFOID not between", value1, value2, "memberinfoid");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("OPENID is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("OPENID is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("OPENID =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("OPENID <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("OPENID >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("OPENID >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("OPENID <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("OPENID <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("OPENID like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("OPENID not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("OPENID in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("OPENID not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("OPENID between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("OPENID not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("SCORE is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Short value) {
            addCriterion("SCORE =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Short value) {
            addCriterion("SCORE <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Short value) {
            addCriterion("SCORE >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Short value) {
            addCriterion("SCORE >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Short value) {
            addCriterion("SCORE <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Short value) {
            addCriterion("SCORE <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Short> values) {
            addCriterion("SCORE in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Short> values) {
            addCriterion("SCORE not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Short value1, Short value2) {
            addCriterion("SCORE between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Short value1, Short value2) {
            addCriterion("SCORE not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andMemberlevelIsNull() {
            addCriterion("MEMBERLEVEL is null");
            return (Criteria) this;
        }

        public Criteria andMemberlevelIsNotNull() {
            addCriterion("MEMBERLEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andMemberlevelEqualTo(Short value) {
            addCriterion("MEMBERLEVEL =", value, "memberlevel");
            return (Criteria) this;
        }

        public Criteria andMemberlevelNotEqualTo(Short value) {
            addCriterion("MEMBERLEVEL <>", value, "memberlevel");
            return (Criteria) this;
        }

        public Criteria andMemberlevelGreaterThan(Short value) {
            addCriterion("MEMBERLEVEL >", value, "memberlevel");
            return (Criteria) this;
        }

        public Criteria andMemberlevelGreaterThanOrEqualTo(Short value) {
            addCriterion("MEMBERLEVEL >=", value, "memberlevel");
            return (Criteria) this;
        }

        public Criteria andMemberlevelLessThan(Short value) {
            addCriterion("MEMBERLEVEL <", value, "memberlevel");
            return (Criteria) this;
        }

        public Criteria andMemberlevelLessThanOrEqualTo(Short value) {
            addCriterion("MEMBERLEVEL <=", value, "memberlevel");
            return (Criteria) this;
        }

        public Criteria andMemberlevelIn(List<Short> values) {
            addCriterion("MEMBERLEVEL in", values, "memberlevel");
            return (Criteria) this;
        }

        public Criteria andMemberlevelNotIn(List<Short> values) {
            addCriterion("MEMBERLEVEL not in", values, "memberlevel");
            return (Criteria) this;
        }

        public Criteria andMemberlevelBetween(Short value1, Short value2) {
            addCriterion("MEMBERLEVEL between", value1, value2, "memberlevel");
            return (Criteria) this;
        }

        public Criteria andMemberlevelNotBetween(Short value1, Short value2) {
            addCriterion("MEMBERLEVEL not between", value1, value2, "memberlevel");
            return (Criteria) this;
        }

        public Criteria andMembermoneyIsNull() {
            addCriterion("MEMBERMONEY is null");
            return (Criteria) this;
        }

        public Criteria andMembermoneyIsNotNull() {
            addCriterion("MEMBERMONEY is not null");
            return (Criteria) this;
        }

        public Criteria andMembermoneyEqualTo(Short value) {
            addCriterion("MEMBERMONEY =", value, "membermoney");
            return (Criteria) this;
        }

        public Criteria andMembermoneyNotEqualTo(Short value) {
            addCriterion("MEMBERMONEY <>", value, "membermoney");
            return (Criteria) this;
        }

        public Criteria andMembermoneyGreaterThan(Short value) {
            addCriterion("MEMBERMONEY >", value, "membermoney");
            return (Criteria) this;
        }

        public Criteria andMembermoneyGreaterThanOrEqualTo(Short value) {
            addCriterion("MEMBERMONEY >=", value, "membermoney");
            return (Criteria) this;
        }

        public Criteria andMembermoneyLessThan(Short value) {
            addCriterion("MEMBERMONEY <", value, "membermoney");
            return (Criteria) this;
        }

        public Criteria andMembermoneyLessThanOrEqualTo(Short value) {
            addCriterion("MEMBERMONEY <=", value, "membermoney");
            return (Criteria) this;
        }

        public Criteria andMembermoneyIn(List<Short> values) {
            addCriterion("MEMBERMONEY in", values, "membermoney");
            return (Criteria) this;
        }

        public Criteria andMembermoneyNotIn(List<Short> values) {
            addCriterion("MEMBERMONEY not in", values, "membermoney");
            return (Criteria) this;
        }

        public Criteria andMembermoneyBetween(Short value1, Short value2) {
            addCriterion("MEMBERMONEY between", value1, value2, "membermoney");
            return (Criteria) this;
        }

        public Criteria andMembermoneyNotBetween(Short value1, Short value2) {
            addCriterion("MEMBERMONEY not between", value1, value2, "membermoney");
            return (Criteria) this;
        }

        public Criteria andOldmoneyIsNull() {
            addCriterion("OLDMONEY is null");
            return (Criteria) this;
        }

        public Criteria andOldmoneyIsNotNull() {
            addCriterion("OLDMONEY is not null");
            return (Criteria) this;
        }

        public Criteria andOldmoneyEqualTo(Short value) {
            addCriterion("OLDMONEY =", value, "oldmoney");
            return (Criteria) this;
        }

        public Criteria andOldmoneyNotEqualTo(Short value) {
            addCriterion("OLDMONEY <>", value, "oldmoney");
            return (Criteria) this;
        }

        public Criteria andOldmoneyGreaterThan(Short value) {
            addCriterion("OLDMONEY >", value, "oldmoney");
            return (Criteria) this;
        }

        public Criteria andOldmoneyGreaterThanOrEqualTo(Short value) {
            addCriterion("OLDMONEY >=", value, "oldmoney");
            return (Criteria) this;
        }

        public Criteria andOldmoneyLessThan(Short value) {
            addCriterion("OLDMONEY <", value, "oldmoney");
            return (Criteria) this;
        }

        public Criteria andOldmoneyLessThanOrEqualTo(Short value) {
            addCriterion("OLDMONEY <=", value, "oldmoney");
            return (Criteria) this;
        }

        public Criteria andOldmoneyIn(List<Short> values) {
            addCriterion("OLDMONEY in", values, "oldmoney");
            return (Criteria) this;
        }

        public Criteria andOldmoneyNotIn(List<Short> values) {
            addCriterion("OLDMONEY not in", values, "oldmoney");
            return (Criteria) this;
        }

        public Criteria andOldmoneyBetween(Short value1, Short value2) {
            addCriterion("OLDMONEY between", value1, value2, "oldmoney");
            return (Criteria) this;
        }

        public Criteria andOldmoneyNotBetween(Short value1, Short value2) {
            addCriterion("OLDMONEY not between", value1, value2, "oldmoney");
            return (Criteria) this;
        }

        public Criteria andTianniu02IsNull() {
            addCriterion("TIANNIU02 is null");
            return (Criteria) this;
        }

        public Criteria andTianniu02IsNotNull() {
            addCriterion("TIANNIU02 is not null");
            return (Criteria) this;
        }

        public Criteria andTianniu02EqualTo(String value) {
            addCriterion("TIANNIU02 =", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02NotEqualTo(String value) {
            addCriterion("TIANNIU02 <>", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02GreaterThan(String value) {
            addCriterion("TIANNIU02 >", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02GreaterThanOrEqualTo(String value) {
            addCriterion("TIANNIU02 >=", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02LessThan(String value) {
            addCriterion("TIANNIU02 <", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02LessThanOrEqualTo(String value) {
            addCriterion("TIANNIU02 <=", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02Like(String value) {
            addCriterion("TIANNIU02 like", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02NotLike(String value) {
            addCriterion("TIANNIU02 not like", value, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02In(List<String> values) {
            addCriterion("TIANNIU02 in", values, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02NotIn(List<String> values) {
            addCriterion("TIANNIU02 not in", values, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02Between(String value1, String value2) {
            addCriterion("TIANNIU02 between", value1, value2, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu02NotBetween(String value1, String value2) {
            addCriterion("TIANNIU02 not between", value1, value2, "tianniu02");
            return (Criteria) this;
        }

        public Criteria andTianniu03IsNull() {
            addCriterion("TIANNIU03 is null");
            return (Criteria) this;
        }

        public Criteria andTianniu03IsNotNull() {
            addCriterion("TIANNIU03 is not null");
            return (Criteria) this;
        }

        public Criteria andTianniu03EqualTo(String value) {
            addCriterion("TIANNIU03 =", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03NotEqualTo(String value) {
            addCriterion("TIANNIU03 <>", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03GreaterThan(String value) {
            addCriterion("TIANNIU03 >", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03GreaterThanOrEqualTo(String value) {
            addCriterion("TIANNIU03 >=", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03LessThan(String value) {
            addCriterion("TIANNIU03 <", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03LessThanOrEqualTo(String value) {
            addCriterion("TIANNIU03 <=", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03Like(String value) {
            addCriterion("TIANNIU03 like", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03NotLike(String value) {
            addCriterion("TIANNIU03 not like", value, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03In(List<String> values) {
            addCriterion("TIANNIU03 in", values, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03NotIn(List<String> values) {
            addCriterion("TIANNIU03 not in", values, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03Between(String value1, String value2) {
            addCriterion("TIANNIU03 between", value1, value2, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu03NotBetween(String value1, String value2) {
            addCriterion("TIANNIU03 not between", value1, value2, "tianniu03");
            return (Criteria) this;
        }

        public Criteria andTianniu04IsNull() {
            addCriterion("TIANNIU04 is null");
            return (Criteria) this;
        }

        public Criteria andTianniu04IsNotNull() {
            addCriterion("TIANNIU04 is not null");
            return (Criteria) this;
        }

        public Criteria andTianniu04EqualTo(String value) {
            addCriterion("TIANNIU04 =", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04NotEqualTo(String value) {
            addCriterion("TIANNIU04 <>", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04GreaterThan(String value) {
            addCriterion("TIANNIU04 >", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04GreaterThanOrEqualTo(String value) {
            addCriterion("TIANNIU04 >=", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04LessThan(String value) {
            addCriterion("TIANNIU04 <", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04LessThanOrEqualTo(String value) {
            addCriterion("TIANNIU04 <=", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04Like(String value) {
            addCriterion("TIANNIU04 like", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04NotLike(String value) {
            addCriterion("TIANNIU04 not like", value, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04In(List<String> values) {
            addCriterion("TIANNIU04 in", values, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04NotIn(List<String> values) {
            addCriterion("TIANNIU04 not in", values, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04Between(String value1, String value2) {
            addCriterion("TIANNIU04 between", value1, value2, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andTianniu04NotBetween(String value1, String value2) {
            addCriterion("TIANNIU04 not between", value1, value2, "tianniu04");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 09 15:34:13 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_INFO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}