package com.tianniu.pojo;

import java.util.ArrayList;
import java.util.List;

public class MemberRecordsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public MemberRecordsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMemberrecordsidIsNull() {
            addCriterion("MEMBERRECORDSID is null");
            return (Criteria) this;
        }

        public Criteria andMemberrecordsidIsNotNull() {
            addCriterion("MEMBERRECORDSID is not null");
            return (Criteria) this;
        }

        public Criteria andMemberrecordsidEqualTo(Short value) {
            addCriterion("MEMBERRECORDSID =", value, "memberrecordsid");
            return (Criteria) this;
        }

        public Criteria andMemberrecordsidNotEqualTo(Short value) {
            addCriterion("MEMBERRECORDSID <>", value, "memberrecordsid");
            return (Criteria) this;
        }

        public Criteria andMemberrecordsidGreaterThan(Short value) {
            addCriterion("MEMBERRECORDSID >", value, "memberrecordsid");
            return (Criteria) this;
        }

        public Criteria andMemberrecordsidGreaterThanOrEqualTo(Short value) {
            addCriterion("MEMBERRECORDSID >=", value, "memberrecordsid");
            return (Criteria) this;
        }

        public Criteria andMemberrecordsidLessThan(Short value) {
            addCriterion("MEMBERRECORDSID <", value, "memberrecordsid");
            return (Criteria) this;
        }

        public Criteria andMemberrecordsidLessThanOrEqualTo(Short value) {
            addCriterion("MEMBERRECORDSID <=", value, "memberrecordsid");
            return (Criteria) this;
        }

        public Criteria andMemberrecordsidIn(List<Short> values) {
            addCriterion("MEMBERRECORDSID in", values, "memberrecordsid");
            return (Criteria) this;
        }

        public Criteria andMemberrecordsidNotIn(List<Short> values) {
            addCriterion("MEMBERRECORDSID not in", values, "memberrecordsid");
            return (Criteria) this;
        }

        public Criteria andMemberrecordsidBetween(Short value1, Short value2) {
            addCriterion("MEMBERRECORDSID between", value1, value2, "memberrecordsid");
            return (Criteria) this;
        }

        public Criteria andMemberrecordsidNotBetween(Short value1, Short value2) {
            addCriterion("MEMBERRECORDSID not between", value1, value2, "memberrecordsid");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("OPENID is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("OPENID is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("OPENID =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("OPENID <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("OPENID >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("OPENID >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("OPENID <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("OPENID <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("OPENID like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("OPENID not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("OPENID in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("OPENID not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("OPENID between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("OPENID not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyIsNull() {
            addCriterion("CHECKINMONEY is null");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyIsNotNull() {
            addCriterion("CHECKINMONEY is not null");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyEqualTo(Short value) {
            addCriterion("CHECKINMONEY =", value, "checkinmoney");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyNotEqualTo(Short value) {
            addCriterion("CHECKINMONEY <>", value, "checkinmoney");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyGreaterThan(Short value) {
            addCriterion("CHECKINMONEY >", value, "checkinmoney");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyGreaterThanOrEqualTo(Short value) {
            addCriterion("CHECKINMONEY >=", value, "checkinmoney");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyLessThan(Short value) {
            addCriterion("CHECKINMONEY <", value, "checkinmoney");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyLessThanOrEqualTo(Short value) {
            addCriterion("CHECKINMONEY <=", value, "checkinmoney");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyIn(List<Short> values) {
            addCriterion("CHECKINMONEY in", values, "checkinmoney");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyNotIn(List<Short> values) {
            addCriterion("CHECKINMONEY not in", values, "checkinmoney");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyBetween(Short value1, Short value2) {
            addCriterion("CHECKINMONEY between", value1, value2, "checkinmoney");
            return (Criteria) this;
        }

        public Criteria andCheckinmoneyNotBetween(Short value1, Short value2) {
            addCriterion("CHECKINMONEY not between", value1, value2, "checkinmoney");
            return (Criteria) this;
        }

        public Criteria andGivescoreIsNull() {
            addCriterion("GIVESCORE is null");
            return (Criteria) this;
        }

        public Criteria andGivescoreIsNotNull() {
            addCriterion("GIVESCORE is not null");
            return (Criteria) this;
        }

        public Criteria andGivescoreEqualTo(Short value) {
            addCriterion("GIVESCORE =", value, "givescore");
            return (Criteria) this;
        }

        public Criteria andGivescoreNotEqualTo(Short value) {
            addCriterion("GIVESCORE <>", value, "givescore");
            return (Criteria) this;
        }

        public Criteria andGivescoreGreaterThan(Short value) {
            addCriterion("GIVESCORE >", value, "givescore");
            return (Criteria) this;
        }

        public Criteria andGivescoreGreaterThanOrEqualTo(Short value) {
            addCriterion("GIVESCORE >=", value, "givescore");
            return (Criteria) this;
        }

        public Criteria andGivescoreLessThan(Short value) {
            addCriterion("GIVESCORE <", value, "givescore");
            return (Criteria) this;
        }

        public Criteria andGivescoreLessThanOrEqualTo(Short value) {
            addCriterion("GIVESCORE <=", value, "givescore");
            return (Criteria) this;
        }

        public Criteria andGivescoreIn(List<Short> values) {
            addCriterion("GIVESCORE in", values, "givescore");
            return (Criteria) this;
        }

        public Criteria andGivescoreNotIn(List<Short> values) {
            addCriterion("GIVESCORE not in", values, "givescore");
            return (Criteria) this;
        }

        public Criteria andGivescoreBetween(Short value1, Short value2) {
            addCriterion("GIVESCORE between", value1, value2, "givescore");
            return (Criteria) this;
        }

        public Criteria andGivescoreNotBetween(Short value1, Short value2) {
            addCriterion("GIVESCORE not between", value1, value2, "givescore");
            return (Criteria) this;
        }

        public Criteria andTradeflownoIsNull() {
            addCriterion("TRADEFLOWNO is null");
            return (Criteria) this;
        }

        public Criteria andTradeflownoIsNotNull() {
            addCriterion("TRADEFLOWNO is not null");
            return (Criteria) this;
        }

        public Criteria andTradeflownoEqualTo(String value) {
            addCriterion("TRADEFLOWNO =", value, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andTradeflownoNotEqualTo(String value) {
            addCriterion("TRADEFLOWNO <>", value, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andTradeflownoGreaterThan(String value) {
            addCriterion("TRADEFLOWNO >", value, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andTradeflownoGreaterThanOrEqualTo(String value) {
            addCriterion("TRADEFLOWNO >=", value, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andTradeflownoLessThan(String value) {
            addCriterion("TRADEFLOWNO <", value, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andTradeflownoLessThanOrEqualTo(String value) {
            addCriterion("TRADEFLOWNO <=", value, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andTradeflownoLike(String value) {
            addCriterion("TRADEFLOWNO like", value, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andTradeflownoNotLike(String value) {
            addCriterion("TRADEFLOWNO not like", value, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andTradeflownoIn(List<String> values) {
            addCriterion("TRADEFLOWNO in", values, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andTradeflownoNotIn(List<String> values) {
            addCriterion("TRADEFLOWNO not in", values, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andTradeflownoBetween(String value1, String value2) {
            addCriterion("TRADEFLOWNO between", value1, value2, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andTradeflownoNotBetween(String value1, String value2) {
            addCriterion("TRADEFLOWNO not between", value1, value2, "tradeflowno");
            return (Criteria) this;
        }

        public Criteria andOpttimeIsNull() {
            addCriterion("OPTTIME is null");
            return (Criteria) this;
        }

        public Criteria andOpttimeIsNotNull() {
            addCriterion("OPTTIME is not null");
            return (Criteria) this;
        }

        public Criteria andOpttimeEqualTo(String value) {
            addCriterion("OPTTIME =", value, "opttime");
            return (Criteria) this;
        }

        public Criteria andOpttimeNotEqualTo(String value) {
            addCriterion("OPTTIME <>", value, "opttime");
            return (Criteria) this;
        }

        public Criteria andOpttimeGreaterThan(String value) {
            addCriterion("OPTTIME >", value, "opttime");
            return (Criteria) this;
        }

        public Criteria andOpttimeGreaterThanOrEqualTo(String value) {
            addCriterion("OPTTIME >=", value, "opttime");
            return (Criteria) this;
        }

        public Criteria andOpttimeLessThan(String value) {
            addCriterion("OPTTIME <", value, "opttime");
            return (Criteria) this;
        }

        public Criteria andOpttimeLessThanOrEqualTo(String value) {
            addCriterion("OPTTIME <=", value, "opttime");
            return (Criteria) this;
        }

        public Criteria andOpttimeLike(String value) {
            addCriterion("OPTTIME like", value, "opttime");
            return (Criteria) this;
        }

        public Criteria andOpttimeNotLike(String value) {
            addCriterion("OPTTIME not like", value, "opttime");
            return (Criteria) this;
        }

        public Criteria andOpttimeIn(List<String> values) {
            addCriterion("OPTTIME in", values, "opttime");
            return (Criteria) this;
        }

        public Criteria andOpttimeNotIn(List<String> values) {
            addCriterion("OPTTIME not in", values, "opttime");
            return (Criteria) this;
        }

        public Criteria andOpttimeBetween(String value1, String value2) {
            addCriterion("OPTTIME between", value1, value2, "opttime");
            return (Criteria) this;
        }

        public Criteria andOpttimeNotBetween(String value1, String value2) {
            addCriterion("OPTTIME not between", value1, value2, "opttime");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNull() {
            addCriterion("PAYTYPE is null");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNotNull() {
            addCriterion("PAYTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPaytypeEqualTo(String value) {
            addCriterion("PAYTYPE =", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotEqualTo(String value) {
            addCriterion("PAYTYPE <>", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThan(String value) {
            addCriterion("PAYTYPE >", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThanOrEqualTo(String value) {
            addCriterion("PAYTYPE >=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThan(String value) {
            addCriterion("PAYTYPE <", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThanOrEqualTo(String value) {
            addCriterion("PAYTYPE <=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLike(String value) {
            addCriterion("PAYTYPE like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotLike(String value) {
            addCriterion("PAYTYPE not like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeIn(List<String> values) {
            addCriterion("PAYTYPE in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotIn(List<String> values) {
            addCriterion("PAYTYPE not in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeBetween(String value1, String value2) {
            addCriterion("PAYTYPE between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotBetween(String value1, String value2) {
            addCriterion("PAYTYPE not between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andStationnameIsNull() {
            addCriterion("STATIONNAME is null");
            return (Criteria) this;
        }

        public Criteria andStationnameIsNotNull() {
            addCriterion("STATIONNAME is not null");
            return (Criteria) this;
        }

        public Criteria andStationnameEqualTo(String value) {
            addCriterion("STATIONNAME =", value, "stationname");
            return (Criteria) this;
        }

        public Criteria andStationnameNotEqualTo(String value) {
            addCriterion("STATIONNAME <>", value, "stationname");
            return (Criteria) this;
        }

        public Criteria andStationnameGreaterThan(String value) {
            addCriterion("STATIONNAME >", value, "stationname");
            return (Criteria) this;
        }

        public Criteria andStationnameGreaterThanOrEqualTo(String value) {
            addCriterion("STATIONNAME >=", value, "stationname");
            return (Criteria) this;
        }

        public Criteria andStationnameLessThan(String value) {
            addCriterion("STATIONNAME <", value, "stationname");
            return (Criteria) this;
        }

        public Criteria andStationnameLessThanOrEqualTo(String value) {
            addCriterion("STATIONNAME <=", value, "stationname");
            return (Criteria) this;
        }

        public Criteria andStationnameLike(String value) {
            addCriterion("STATIONNAME like", value, "stationname");
            return (Criteria) this;
        }

        public Criteria andStationnameNotLike(String value) {
            addCriterion("STATIONNAME not like", value, "stationname");
            return (Criteria) this;
        }

        public Criteria andStationnameIn(List<String> values) {
            addCriterion("STATIONNAME in", values, "stationname");
            return (Criteria) this;
        }

        public Criteria andStationnameNotIn(List<String> values) {
            addCriterion("STATIONNAME not in", values, "stationname");
            return (Criteria) this;
        }

        public Criteria andStationnameBetween(String value1, String value2) {
            addCriterion("STATIONNAME between", value1, value2, "stationname");
            return (Criteria) this;
        }

        public Criteria andStationnameNotBetween(String value1, String value2) {
            addCriterion("STATIONNAME not between", value1, value2, "stationname");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("DELETEFLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("DELETEFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagEqualTo(String value) {
            addCriterion("DELETEFLAG =", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotEqualTo(String value) {
            addCriterion("DELETEFLAG <>", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThan(String value) {
            addCriterion("DELETEFLAG >", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETEFLAG >=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThan(String value) {
            addCriterion("DELETEFLAG <", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(String value) {
            addCriterion("DELETEFLAG <=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLike(String value) {
            addCriterion("DELETEFLAG like", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotLike(String value) {
            addCriterion("DELETEFLAG not like", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIn(List<String> values) {
            addCriterion("DELETEFLAG in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotIn(List<String> values) {
            addCriterion("DELETEFLAG not in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagBetween(String value1, String value2) {
            addCriterion("DELETEFLAG between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotBetween(String value1, String value2) {
            addCriterion("DELETEFLAG not between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andCardamtIsNull() {
            addCriterion("CARDAMT is null");
            return (Criteria) this;
        }

        public Criteria andCardamtIsNotNull() {
            addCriterion("CARDAMT is not null");
            return (Criteria) this;
        }

        public Criteria andCardamtEqualTo(String value) {
            addCriterion("CARDAMT =", value, "cardamt");
            return (Criteria) this;
        }

        public Criteria andCardamtNotEqualTo(String value) {
            addCriterion("CARDAMT <>", value, "cardamt");
            return (Criteria) this;
        }

        public Criteria andCardamtGreaterThan(String value) {
            addCriterion("CARDAMT >", value, "cardamt");
            return (Criteria) this;
        }

        public Criteria andCardamtGreaterThanOrEqualTo(String value) {
            addCriterion("CARDAMT >=", value, "cardamt");
            return (Criteria) this;
        }

        public Criteria andCardamtLessThan(String value) {
            addCriterion("CARDAMT <", value, "cardamt");
            return (Criteria) this;
        }

        public Criteria andCardamtLessThanOrEqualTo(String value) {
            addCriterion("CARDAMT <=", value, "cardamt");
            return (Criteria) this;
        }

        public Criteria andCardamtLike(String value) {
            addCriterion("CARDAMT like", value, "cardamt");
            return (Criteria) this;
        }

        public Criteria andCardamtNotLike(String value) {
            addCriterion("CARDAMT not like", value, "cardamt");
            return (Criteria) this;
        }

        public Criteria andCardamtIn(List<String> values) {
            addCriterion("CARDAMT in", values, "cardamt");
            return (Criteria) this;
        }

        public Criteria andCardamtNotIn(List<String> values) {
            addCriterion("CARDAMT not in", values, "cardamt");
            return (Criteria) this;
        }

        public Criteria andCardamtBetween(String value1, String value2) {
            addCriterion("CARDAMT between", value1, value2, "cardamt");
            return (Criteria) this;
        }

        public Criteria andCardamtNotBetween(String value1, String value2) {
            addCriterion("CARDAMT not between", value1, value2, "cardamt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 09 15:34:13 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MEMBER_RECORDS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}