package com.tianniu.pojo;

public class MemberRecords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_RECORDS.MEMBERRECORDSID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private Short memberrecordsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_RECORDS.OPENID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_RECORDS.CHECKINMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private Short checkinmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_RECORDS.GIVESCORE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private Short givescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_RECORDS.TRADEFLOWNO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String tradeflowno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_RECORDS.OPTTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String opttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_RECORDS.PAYTYPE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_RECORDS.STATIONNAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String stationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_RECORDS.REMARKS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_RECORDS.DELETEFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_RECORDS.CARDAMT
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    private String cardamt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_RECORDS.MEMBERRECORDSID
     *
     * @return the value of MEMBER_RECORDS.MEMBERRECORDSID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getMemberrecordsid() {
        return memberrecordsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_RECORDS.MEMBERRECORDSID
     *
     * @param memberrecordsid the value for MEMBER_RECORDS.MEMBERRECORDSID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setMemberrecordsid(Short memberrecordsid) {
        this.memberrecordsid = memberrecordsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_RECORDS.OPENID
     *
     * @return the value of MEMBER_RECORDS.OPENID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_RECORDS.OPENID
     *
     * @param openid the value for MEMBER_RECORDS.OPENID
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_RECORDS.CHECKINMONEY
     *
     * @return the value of MEMBER_RECORDS.CHECKINMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getCheckinmoney() {
        return checkinmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_RECORDS.CHECKINMONEY
     *
     * @param checkinmoney the value for MEMBER_RECORDS.CHECKINMONEY
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setCheckinmoney(Short checkinmoney) {
        this.checkinmoney = checkinmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_RECORDS.GIVESCORE
     *
     * @return the value of MEMBER_RECORDS.GIVESCORE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public Short getGivescore() {
        return givescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_RECORDS.GIVESCORE
     *
     * @param givescore the value for MEMBER_RECORDS.GIVESCORE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setGivescore(Short givescore) {
        this.givescore = givescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_RECORDS.TRADEFLOWNO
     *
     * @return the value of MEMBER_RECORDS.TRADEFLOWNO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getTradeflowno() {
        return tradeflowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_RECORDS.TRADEFLOWNO
     *
     * @param tradeflowno the value for MEMBER_RECORDS.TRADEFLOWNO
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setTradeflowno(String tradeflowno) {
        this.tradeflowno = tradeflowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_RECORDS.OPTTIME
     *
     * @return the value of MEMBER_RECORDS.OPTTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getOpttime() {
        return opttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_RECORDS.OPTTIME
     *
     * @param opttime the value for MEMBER_RECORDS.OPTTIME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setOpttime(String opttime) {
        this.opttime = opttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_RECORDS.PAYTYPE
     *
     * @return the value of MEMBER_RECORDS.PAYTYPE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_RECORDS.PAYTYPE
     *
     * @param paytype the value for MEMBER_RECORDS.PAYTYPE
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_RECORDS.STATIONNAME
     *
     * @return the value of MEMBER_RECORDS.STATIONNAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getStationname() {
        return stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_RECORDS.STATIONNAME
     *
     * @param stationname the value for MEMBER_RECORDS.STATIONNAME
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setStationname(String stationname) {
        this.stationname = stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_RECORDS.REMARKS
     *
     * @return the value of MEMBER_RECORDS.REMARKS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_RECORDS.REMARKS
     *
     * @param remarks the value for MEMBER_RECORDS.REMARKS
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_RECORDS.DELETEFLAG
     *
     * @return the value of MEMBER_RECORDS.DELETEFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_RECORDS.DELETEFLAG
     *
     * @param deleteflag the value for MEMBER_RECORDS.DELETEFLAG
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_RECORDS.CARDAMT
     *
     * @return the value of MEMBER_RECORDS.CARDAMT
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public String getCardamt() {
        return cardamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_RECORDS.CARDAMT
     *
     * @param cardamt the value for MEMBER_RECORDS.CARDAMT
     *
     * @mbggenerated Wed Jan 09 15:34:13 CST 2019
     */
    public void setCardamt(String cardamt) {
        this.cardamt = cardamt;
    }
}